include:
    - board: nice_nano@2//zmk
      shield: lily58_left nice_view_adapter nice_epaper
    - board: nice_nano@2//zmk
      shield: lily58_right nice_view_adapter nice_epaper
    - board: nice_nano@2//zmk
      shield: settings_reset
